# Generated by Django 3.0.2 on 2020-01-29 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_data',
            fields=[
                ('username', models.CharField(default=None, max_length=200, primary_key=True, serialize=False)),
                ('password', models.CharField(default=None, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default=None, max_length=3000)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('scope', models.CharField(default=None, max_length=20)),
                ('image', models.ImageField(upload_to='blogging/media')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogging.User_data')),
            ],
        ),
    ]
